name: nation_code_picker
description: "This package provides a widget that allows you to select country dialing codes in your applications."
version: 1.2.2
repository: https://github.com/enescerrahoglu/nation_code_picker
homepage: https://enescerrahoglu.com/

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/flags/
    - assets/locale/
