enum NationCodes {
  tr("Türkiye", "TR", "+90"),
  af("افغانستان", "AF", "+93"),
  ax("Åland", "AX", "+358"),
  al("Shqipëria", "AL", "+355"),
  dz("الجزائر", "DZ", "+213"),
  as("American Samoa", "AS", "+1684"),
  ad("Andorra", "AD", "+376"),
  ao("Angola", "AO", "+244"),
  ai("Anguilla", "AI", "+1264"),
  aq("Antarctica", "AQ", "+672"),
  ag("Antigua and Barbuda", "AG", "+1268"),
  ar("Argentina", "AR", "+54"),
  am("Հայաստան", "AM", "+374"),
  aw("Aruba", "AW", "+297"),
  au("Australia", "AU", "+61"),
  at("Österreich", "AT", "+43"),
  az("Azərbaycan", "AZ", "+994"),
  bs("Bahamas", "BS", "+1242"),
  bh("‏البحرين", "BH", "+973"),
  bd("Bangladesh", "BD", "+880"),
  bb("Barbados", "BB", "+1246"),
  by("Белару́сь", "BY", "+375"),
  be("België", "BE", "+32"),
  bz("Belize", "BZ", "+501"),
  bj("Bénin", "BJ", "+229"),
  bm("Bermuda", "BM", "+1441"),
  bt("ʼbrug-yul", "BT", "+975"),
  bo("Bolivia", "BO", "+591"),
  ba("Bosna i Hercegovina", "BA", "+387"),
  bw("Botswana", "BW", "+267"),
  bv("Bouvetøya", "BV", "+47"),
  br("Brasil", "BR", "+55"),
  io("British Indian Ocean Territory", "IO", "+246"),
  bn("Negara Brunei Darussalam", "BN", "+673"),
  bg("България", "BG", "+359"),
  bf("Burkina Faso", "BF", "+226"),
  bi("Burundi", "BI", "+257"),
  kh("Cambodia", "KH", "+855"),
  cm("Cameroon", "CM", "+237"),
  ca("Canada", "CA", "+1"),
  cv("Cabo Verde", "CV", "+238"),
  ky("Cayman Islands", "KY", "+1345"),
  cf("Ködörösêse tî Bêafrîka", "CF", "+236"),
  td("Tchad", "TD", "+235"),
  cl("Chile", "CL", "+56"),
  cn("中国", "CN", "+86"),
  cx("Christmas Island", "CX", "+61"),
  cc("Cocos (Keeling) Islands", "CC", "+61"),
  co("Colombia", "CO", "+57"),
  km("Komori", "KM", "+269"),
  cg("République du Congo", "CG", "+242"),
  cd("République démocratique du Congo", "CD", "+243"),
  ck("Cook Islands", "CK", "+682"),
  cr("Costa Rica", "CR", "+506"),
  ci("Côte d'Ivoire", "CI", "+225"),
  hr("Hrvatska", "HR", "+385"),
  cu("Cuba", "CU", "+53"),
  cy("Κύπρος", "CY", "+357"),
  cz("Česká republika", "CZ", "+420"),
  dk("Danmark", "DK", "+45"),
  dj("Djibouti", "DJ", "+253"),
  dm("Dominica", "DM", "+1767"),
  do_("República Dominicana", "DO", "+1"),
  ec("Ecuador", "EC", "+593"),
  eg("مصر‎", "EG", "+20"),
  sv("El Salvador", "SV", "+503"),
  gq("Guinea Ecuatorial", "GQ", "+240"),
  er("ኤርትራ", "ER", "+291"),
  ee("Eesti", "EE", "+372"),
  et("ኢትዮጵያ", "ET", "+251"),
  fk("Falkland Islands", "FK", "+500"),
  fo("Føroyar", "FO", "+298"),
  fj("Fiji", "FJ", "+679"),
  fi("Suomi", "FI", "+358"),
  fr("France", "FR", "+33"),
  gf("Guyane française", "GF", "+594"),
  pf("Polynésie française", "PF", "+689"),
  tf("Territoire des Terres australes et antarctiques fr", "TF", "+262"),
  ga("Gabon", "GA", "+241"),
  gm("Gambia", "GM", "+220"),
  ge("საქართველო", "GE", "+995"),
  de("Deutschland", "DE", "+49"),
  gh("Ghana", "GH", "+233"),
  gi("Gibraltar", "GI", "+350"),
  gr("Ελλάδα", "GR", "+30"),
  gl("Kalaallit Nunaat", "GL", "+299"),
  gd("Grenada", "GD", "+1473"),
  gp("Guadeloupe", "GP", "+590"),
  gu("Guam", "GU", "+1671"),
  gt("Guatemala", "GT", "+502"),
  gg("Guernsey", "GG", "+44"),
  gn("Guinée", "GN", "+224"),
  gw("Guiné-Bissau", "GW", "+245"),
  gy("Guyana", "GY", "+592"),
  ht("Haïti", "HT", "+509"),
  hm("Heard Island and McDonald Islands", "HM", "+0"),
  va("Vaticano", "VA", "+379"),
  hn("Honduras", "HN", "+504"),
  hk("香港", "HK", "+852"),
  hu("Magyarország", "HU", "+36"),
  is_("Ísland", "IS", "+354"),
  in_("भारत", "IN", "+91"),
  id("Indonesia", "ID", "+62"),
  ir("ایران", "IR", "+98"),
  iq("العراق", "IQ", "+964"),
  ie("Éire", "IE", "+353"),
  im("Isle of Man", "IM", "+44"),
  il("ישראל", "IL", "+972"),
  it("Italia", "IT", "+39"),
  jm("Jamaica", "JM", "+1876"),
  jp("日本", "JP", "+81"),
  je("Jersey", "JE", "+44"),
  jo("الأردن", "JO", "+962"),
  kz("Қазақстан", "KZ", "+7"),
  ke("Kenya", "KE", "+254"),
  ki("Kiribati", "KI", "+686"),
  kp("북한", "KP", "+850"),
  kr("대한민국", "KR", "+82"),
  xk("Republika e Kosovës", "XK", "+383"),
  kw("الكويت", "KW", "+965"),
  kg("Кыргызстан", "KG", "+996"),
  la("ສປປລາວ", "LA", "+856"),
  lv("Latvija", "LV", "+371"),
  lb("لبنان", "LB", "+961"),
  ls("Lesotho", "LS", "+266"),
  lr("Liberia", "LR", "+231"),
  ly("‏ليبيا", "LY", "+218"),
  li("Liechtenstein", "LI", "+423"),
  lt("Lietuva", "LT", "+370"),
  lu("Luxembourg", "LU", "+352"),
  mo("澳門", "MO", "+853"),
  mk("Македонија", "MK", "+389"),
  mg("Madagasikara", "MG", "+261"),
  mw("Malawi", "MW", "+265"),
  my("Malaysia", "MY", "+60"),
  mv("Maldives", "MV", "+960"),
  ml("Mali", "ML", "+223"),
  mt("Malta", "MT", "+356"),
  mh("M̧ajeļ", "MH", "+692"),
  mq("Martinique", "MQ", "+596"),
  mr("موريتانيا", "MR", "+222"),
  mu("Maurice", "MU", "+230"),
  yt("Mayotte", "YT", "+262"),
  mx("México", "MX", "+52"),
  fm("Micronesia", "FM", "+691"),
  md("Moldova", "MD", "+373"),
  mc("Monaco", "MC", "+377"),
  mn("Монгол улс", "MN", "+976"),
  me("Црна Гора", "ME", "+382"),
  ms("Montserrat", "MS", "+1664"),
  ma("المغرب", "MA", "+212"),
  mz("Moçambique", "MZ", "+258"),
  mm("Myanmar", "MM", "+95"),
  na("Namibia", "NA", "+264"),
  nr("Nauru", "NR", "+674"),
  np("नेपाल", "NP", "+977"),
  nl("Nederland", "NL", "+31"),
  nc("Nouvelle-Calédonie", "NC", "+687"),
  nz("New Zealand", "NZ", "+64"),
  ni("Nicaragua", "NI", "+505"),
  ne("Niger", "NE", "+227"),
  ng("Nigeria", "NG", "+234"),
  nu("Niue", "NU", "+683"),
  nf("Norfolk Island", "NF", "+672"),
  mp("Northern Mariana Islands", "MP", "+1670"),
  no("Norge", "NO", "+47"),
  om("عمان", "OM", "+968"),
  pk("پاکستان", "PK", "+92"),
  pw("Belau", "PW", "+680"),
  ps("فلسطين", "PS", "+970"),
  pa("Panamá", "PA", "+507"),
  pg("Papua Niugini", "PG", "+675"),
  py("Paraguay", "PY", "+595"),
  pe("Perú", "PE", "+51"),
  ph("Pilipinas", "PH", "+63"),
  pn("Pitcairn Islands", "PN", "+64"),
  pl("Polska", "PL", "+48"),
  pt("Portugal", "PT", "+351"),
  pr("Puerto Rico", "PR", "+1"),
  qa("قطر", "QA", "+974"),
  re("La Réunion", "RE", "+262"),
  ro("România", "RO", "+40"),
  ru("Россия", "RU", "+7"),
  rw("Rwanda", "RW", "+250"),
  bl("Saint Barthélemy", "BL", "+590"),
  sh("Saint Helena", "SH", "+290"),
  kn("Saint Kitts and Nevis", "KN", "+1869"),
  lc("Saint Lucia", "LC", "+1758"),
  mf("Saint-Martin", "MF", "+590"),
  pm("Saint-Pierre-et-Miquelon", "PM", "+508"),
  vc("Saint Vincent and the Grenadines", "VC", "+1784"),
  ws("Samoa", "WS", "+685"),
  sm("San Marino", "SM", "+378"),
  st("São Tomé e Príncipe", "ST", "+239"),
  sa("المملكة العربية السعودية", "SA", "+966"),
  sn("Sénégal", "SN", "+221"),
  rs("Србија", "RS", "+381"),
  sc("Seychelles", "SC", "+248"),
  sl("Sierra Leone", "SL", "+232"),
  sg("Singapore", "SG", "+65"),
  sx("Sint Maarten", "SX", "+1721"),
  sk("Slovensko", "SK", "+421"),
  si("Slovenija", "SI", "+386"),
  sb("Solomon Islands", "SB", "+677"),
  so("Soomaaliya", "SO", "+252"),
  za("South Africa", "ZA", "+27"),
  ss("جنوب السودان", "SS", "+211"),
  es("España", "ES", "+34"),
  lk("ශ්‍රී ලංකාව", "LK", "+94"),
  sd("السودان", "SD", "+249"),
  sr("Suriname", "SR", "+597"),
  sj("Svalbard og Jan Mayen", "SJ", "+47"),
  sz("Swaziland", "SZ", "+268"),
  se("Sverige", "SE", "+46"),
  ch("Schweiz", "CH", "+41"),
  sy("سوريا", "SY", "+963"),
  tw("台灣", "TW", "+886"),
  tj("Тоҷикистон", "TJ", "+992"),
  tz("Tanzania", "TZ", "+255"),
  th("ประเทศไทย", "TH", "+66"),
  tl("Timor-Leste", "TL", "+670"),
  tg("Togo", "TG", "+228"),
  tk("Tokelau", "TK", "+690"),
  to("Tonga", "TO", "+676"),
  tt("Trinidad and Tobago", "TT", "+1868"),
  tn("تونس", "TN", "+216"),
  tm("Türkmenistan", "TM", "+993"),
  tc("Turks and Caicos Islands", "TC", "+1649"),
  tv("Tuvalu", "TV", "+688"),
  ug("Uganda", "UG", "+256"),
  ua("Україна", "UA", "+380"),
  ae("الإمارات العربية المتحدة", "AE", "+971"),
  gb("United Kingdom", "GB", "+44"),
  us("United States", "US", "+1"),
  uy("Uruguay", "UY", "+598"),
  uz("O‘zbekiston", "UZ", "+998"),
  vu("Vanuatu", "VU", "+678"),
  ve("Venezuela", "VE", "+58"),
  vn("Việt Nam", "VN", "+84"),
  vg("Virgin Islands (British)", "VG", "+1284"),
  vi("Virgin Islands (U.S.)", "VI", "+1340"),
  wf("Wallis et Futuna", "WF", "+681"),
  ye("اليَمَن", "YE", "+967"),
  zm("Zambia", "ZM", "+260"),
  zw("Zimbabwe", "ZW", "+263");

  const NationCodes(this.name, this.code, this.dialCode);

  final String name;
  final String code;
  final String dialCode;
}
